### ISSUE TITLE
[Feature] Custom Disk

### ISSUE THREAD

**Issue by mydnic** [tomatophp/filament-browser#6]
Hello

I'd like to use a filament plugin like this one, but my goal is to browse through files and folders from a S3 bucket.

Is it possible to use a different disk (s3) and not only browsing local files ?

Thanks

**Comment by fadymondy** [comment]
hi @mydnic if you need to use a custom disk just use [Filament Media Manager](https://github.com/tomatophp/filament-media-manager)

**Comment by mydnic** [comment]
@3x1io unfortunately that won't work because it requires spatie-media-library package, and thus having a database entry for every file.

In my case I just need a file browser but for a s3 bucket, the files in there does not have a Model/entry in the database

**Comment by FabioMezzo** [comment]
Hi @mydnic, did you solve it?

**Comment by mydnic** [comment]
> Hi [@mydnic](https://github.com/mydnic), did you solve it?

@FabioMezzo I did not solve it... AFAIK there's simply no package for that
